"""add users and user_preferences tables

Revision ID: b599d122034a
Revises: 
Create Date: 2025-10-03 23:02:10.511312+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b599d122034a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address (from Google OAuth). Must be unique."),
    sa.Column('name', sa.String(length=100), nullable=False, comment="User's display name (from Google OAuth)"),
    sa.Column('profile_picture', sa.String(length=255), nullable=True, comment="URL to user's profile picture (from Google OAuth)"),
    sa.Column('profession', sa.String(length=100), nullable=True, comment="User's profession/occupation"),
    sa.Column('date_of_birth', sa.Date(), nullable=True, comment="User's date of birth"),
    sa.Column('timezone', sa.String(length=50), nullable=False, comment="User's timezone for scheduling notifications"),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether user account is active'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='Last time user logged in (UTC)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incrementing primary key'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when record was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Foreign key to users table'),
    sa.Column('update_frequency', sa.Enum('DAILY', 'EVERY_3_DAYS', 'WEEKLY', 'EVERY_2_WEEKS', 'MONTHLY', name='updatefrequency'), nullable=False, comment='How often user receives content digests'),
    sa.Column('summary_length', sa.Enum('CONCISE', 'STANDARD', 'DETAILED', name='summarylength'), nullable=False, comment='Preferred summary detail level'),
    sa.Column('email_notifications_enabled', sa.Boolean(), nullable=False, comment='Whether to send email notifications'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incrementing primary key'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_preferences_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
