"""add channels, user_subscriptions, and content_items tables

Revision ID: 9aae404a44eb
Revises: 0b0b03ab19f5
Create Date: 2025-10-04 07:24:31.995881+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9aae404a44eb'
down_revision = '0b0b03ab19f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('source_type', sa.Enum('YOUTUBE', 'REDDIT', 'BLOG', name='contentsourcetype'), nullable=False, comment='Type of content source (youtube, reddit, blog)'),
    sa.Column('source_identifier', sa.String(length=255), nullable=False, comment='Platform-specific identifier (channel_id, subreddit, feed_url)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Channel/source name'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Channel description'),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True, comment='Channel thumbnail/logo URL'),
    sa.Column('subscriber_count', sa.Integer(), nullable=False, comment='Number of users subscribed to this channel'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this channel is active (not deleted/banned)'),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True, comment='Last time content was fetched from this channel (UTC)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incrementing primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels')),
    sa.UniqueConstraint('source_type', 'source_identifier', name='uq_channel_source')
    )
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channels_source_type'), ['source_type'], unique=False)

    op.create_table('content_items',
    sa.Column('channel_id', sa.Integer(), nullable=False, comment='Foreign key to channels table'),
    sa.Column('external_id', sa.String(length=255), nullable=False, comment='Platform-specific content ID (video_id, post_id, article_url)'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Content title'),
    sa.Column('content_body', sa.Text(), nullable=False, comment='Full content text (transcript, post, article)'),
    sa.Column('author', sa.String(length=100), nullable=False, comment='Content author/creator name'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False, comment='When content was originally published (UTC)'),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', name='processingstatus'), nullable=False, comment='Processing pipeline status'),
    sa.Column('content_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Platform-specific metadata (JSON)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if processing failed'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incrementing primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_content_items_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_items')),
    sa.UniqueConstraint('channel_id', 'external_id', name='uq_channel_content')
    )
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_items_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_items_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_items_published_at'), ['published_at'], unique=False)

    op.create_table('user_subscriptions',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Foreign key to users table'),
    sa.Column('channel_id', sa.Integer(), nullable=False, comment='Foreign key to channels table'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this subscription is active'),
    sa.Column('custom_display_name', sa.String(length=100), nullable=True, comment="User's custom name for this channel (optional)"),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False, comment='Whether to notify user about new content from this channel'),
    sa.Column('last_shown_at', sa.DateTime(timezone=True), nullable=True, comment='Last time content from this channel was shown to this user (UTC)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incrementing primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_user_subscriptions_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_subscriptions')),
    sa.UniqueConstraint('user_id', 'channel_id', name='uq_user_channel')
    )
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_subscriptions_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_subscriptions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_subscriptions_channel_id'))

    op.drop_table('user_subscriptions')
    with op.batch_alter_table('content_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_items_published_at'))
        batch_op.drop_index(batch_op.f('ix_content_items_processing_status'))
        batch_op.drop_index(batch_op.f('ix_content_items_channel_id'))

    op.drop_table('content_items')
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channels_source_type'))

    op.drop_table('channels')
    # ### end Alembic commands ###
