"""add content_sources table

Revision ID: 0b0b03ab19f5
Revises: 91a2e5c46f1c
Create Date: 2025-10-04 00:07:20.502171+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b0b03ab19f5'
down_revision = '91a2e5c46f1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_sources',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Foreign key to users table'),
    sa.Column('source_type', sa.Enum('YOUTUBE', 'REDDIT', 'BLOG', name='contentsourcetype'), nullable=False, comment='Type of content source (youtube, reddit, blog)'),
    sa.Column('source_identifier', sa.String(length=255), nullable=False, comment='Platform-specific identifier (channel_id, subreddit, feed_url)'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='User-friendly display name'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this source is active'),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True, comment='Last time content was fetched from this source (UTC)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incrementing primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_content_sources_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_sources'))
    )
    with op.batch_alter_table('content_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_sources_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_sources_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_sources_user_id'))
        batch_op.drop_index(batch_op.f('ix_content_sources_source_type'))

    op.drop_table('content_sources')
    # ### end Alembic commands ###
